version: '3'

services:

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: dbmigrate
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: migrate_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_USER: dbmigrate
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_DATABASE: migrate_test
    healthcheck:
      test: "/usr/bin/mysql --user=dbmigrate --password=mysecretpassword --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 5s
      retries: 10

  etcd:
    image: elcolio/etcd
    restart: always
    ports:
      - 2379:2379

  consul:
    image: consul:latest
    restart: always
    ports:
      - 8500:8500