postgres:
  image: postgres:alpine
  restart: always
  ports:
    - 5433:5432
  environment:
    POSTGRES_USER: dbmigrate
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_DB: migrate_test

mysql:
  image: mysql:latest
  restart: always
  ports:
    - 3307:3306
  environment:
    MYSQL_ROOT_PASSWORD: mysecretpassword
    MYSQL_USER: dbmigrate
    MYSQL_PASSWORD: mysecretpassword
    MYSQL_DATABASE: migrate_test