# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brew:
  # Repository to push the tap to.
  github:
    owner: dafanasev
    name: dbmigrate

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: Dmitrii Afanasev
    email: nuclear.tools@gmail.com

  # Your app's homepage.
  # Default is empty.
  homepage: "https://github.com/dafanasev/dbmigrate/"

  # Your app's description.
  # Default is empty.
  description: "sql database migration tool"